feat: Link preview
syusui-s/rabbit pull request #73
Opened 2023-11-20 16:36 UTC by kunigaku

Linkのプレビューを表示します。
<img width="311" alt="スクリーンショット 2023-11-21 1 34 13" src="https://github.com/syusui-s/rabbit/assets/1298867/2f8e967d-4b97-4c37-88d4-00b4d3fa3f6e">

対応するプレビューは以下の通り。

- Xの埋め込みツイート
- Youtubeの埋め込み動画
- OGPをfetchしてtitle, description, imageを表示。ホワイトリストでwww3.nhk.or.jpのみ

2023-11-20 16:37 UTC, kunigaku commented
--no-verifyでコミットしてます。
現状エラーがいっぱい出ています。

2023-11-23 01:41 UTC, syusui-s requested changes
こちら修正いただけると嬉しいです。

2023-11-23 01:41 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +          <div class="youtube-embed">
Tailwindを使っているため、以下のように指定してください。

```suggestion
          <div class="w-full aspect-video">
```

- https://tailwindcss.com/docs/width
- https://tailwindcss.com/docs/aspect-ratio

2023-11-23 01:41 UTC, syusui-s commented on src/index.css
> +.youtube-embed {
Tailwindを使うようにしたいため、こちらのCSSの変更は戻しておいていただけると嬉しいです。
（PreviewedLink.tsxの116行目を参照）

2023-11-23 01:41 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +          <a class={props.class} href={props.href} target="_blank" rel="noreferrer noopener">
`<a>`を直接使うのではなく、`SafeLink.tsx`を代わりに使っていただけると嬉しいです

2023-11-23 01:41 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +          <blockquote class="twitter-tweet">
`.eslintrc.js`の`tailwindcss` > `whitelist` の最後にこれを加えていただけると嬉しいです:

```
// third party
'twitter-tweet'
```

2023-11-23 01:41 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +      window.twttr?.widgets.load();
`?.`がもう一つ必要そうです: `window.twttr?.widgets?.load();`

---

`twttr`の型定義がないため、型定義が必要です。以下のようにファイルを作って定義してあげると良いと思います。

`src/types/twitterWidget.ts`

```typescript
type TwitterWidgetAPI = {
  widgets: {
    load(elem?: HTMLElement): void;
  },
};

declare global {
  interface Window {
    twttr?: TwitterWidgetAPI;
  }
}
```

---

これは対応が難しそうであれば私の方で実施します。

ドキュメントによると、DOM要素を渡すとパフォーマンスで良いそうです
https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/guides/scripting-loading-and-initialization

```
let twitterRef: HTMLQuoteElement | undefined;

createEffect(() => {
  if (isTwitter()) {
    window.twttr?.widgets?.load(twitterRef);
  }
});

// ... 中略 ...
<blockquote ref={twitterRef} class="twitter-tweet">
```

2023-11-23 01:41 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +  fetchOgpContents(new URL(props.href.toString()));
最初の一回だけ実行したいので、`solid`の`onMount`を使っていただけると嬉しいです:

```suggestion
onMount(() => {
  fetchOgpContents(new URL(props.href.toString()));
});
```

2023-11-23 16:38 UTC, syusui-s requested changes
エラー修正や指摘修正のほどありがとうございます！
動作確認もできました。

すみませんが、何点か追加で直していただけると嬉しいところがあります。

2023-11-23 16:38 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +    iframeUrl.pathname += originalUrl.searchParams.get('v');
`youtu.be`もサポートできるようにしたいです:

```suggestion
if (originalUrl.host === 'youtu.be') {
  iframeUrl.pathname += originalUrl.host
} else {
  iframeUrl.pathname += originalUrl.searchParams.get('v');
}
```

2023-11-23 16:38 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +    iframeUrl.searchParams.set('origin', window.location.href);
```suggestion
    iframeUrl.searchParams.set('origin', window.location.origin);
```

URL全体ではなく、`origin`を渡せば良いようです。

2023-11-23 16:38 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +  });
Reactの習慣に倣って、`ref`→状態関連→その他の関数→createEffect→onMountの順にしていただけると嬉しいです:

```suggestion
  let twitterRef: HTMLQuoteElement | undefined;

  const initialOgp: OgpContents = { title: '', description: '', image: null, url: null };
  const [getOgpContents, setOgpContents] = createSignal(initialOgp);

  const isSafe = () => {
    try {
      const url = new URL(props.href.toString());
      return url.protocol === 'https:' || url.protocol === 'http:';
    } catch {
      return false;
    }
  };

  const updateOgpContents = async () => {
    const ogp = await fetchOgpContents(new URL(props.href.toString()));
    if (ogp != null) {
      setOgpContents(ogp);
    }
  };
  
  createEffect(() => {
    if (isTwitterUrl(props.href.toString())) {
      window.twttr?.widgets?.load(twitterRef);
    }
  });
  
  onMount(() => {
    updateOgpContents()
      .then(() => {})
      .catch(() => {});
  });
```

2023-11-23 16:38 UTC, syusui-s commented on src/utils/url.ts
> +    );
`youtu.be`もサポートしたいので、以下の条件も加えていただけると嬉しいです

```suggestion
    ) || (
      url.protocol === 'https:' &&
      url.host === 'youtu.be' &&
      url.pathname.lastIndexOf('/') === 0
    );
```

2023-11-23 16:38 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +import '@/types/twitterWidget.d';
私の環境だと、この行があるとエラーで `npm run dev` が動きませんでした。

`d.ts`の定義は恐らくグローバルに読み込まれるはずなので、この行はなくても大丈夫だと思います。

2023-11-23 16:38 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +          <div class="aspect-video w-full">
少しmarginがあると嬉しいです:

```suggestion
          <div class="aspect-video my-2 w-full">
```

2023-11-24 15:04 UTC, kunigaku commented
レビュー指摘を修正しました！

2023-11-24 23:55 UTC, syusui-s requested changes
すみません、一箇所だけlinterに引っかかりそうな箇所がありました。

他にもコメントありますが、もし直すのが面倒でしたら後で私の方で直しておきます。

2023-11-24 23:55 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +        <Match when={getOgpContents().url === null}>
必須ではないので、残してあれば私の方で直します

nullの場合の条件を消して、130行目の内容を110行目のfallbackに移せるとコードがわかりやすくなると思います

2023-11-24 23:55 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +        <Match when={getOgpContents().url !== null}>
必須ではないので、残してあれば私の方で直します

keyedを使うと、引数がnullやundefinedでない場合のみ関数が実行されます。

```suggestion
        <Match when={getOgpContents()} keyed>
          ｛(ogp) => (中身)}
        </Match>
```

2023-11-24 23:55 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +      const url = new URL(props.href.toString());
```suggestion
      const url = new URL(props.href);
```

2023-11-24 23:55 UTC, syusui-s commented on src/components/utils/PreviewedLink.tsx
> +    const ogp = await fetchOgpContents(new URL(props.href.toString()));
```suggestion
    const ogp = await fetchOgpContents(new URL(props.href));
```

2023-11-25 06:16 UTC, kunigaku commented
レビュー指摘を修正しました！

2023-11-25 10:15 UTC, syusui-s approved these changes
ありがとうございます！LGTMです。

マージします

2023-11-25 10:15 UTC, merged